FROM registry.suse.com/bci/golang:1.23

ARG DAPPER_HOST_ARCH
ENV ARCH=$DAPPER_HOST_ARCH

RUN zypper -n install tar gzip bash git gcc docker vim less file curl wget ca-certificates

# The docker version in dapper is too old to have buildx. Install it manually.
RUN curl -sSfL https://github.com/docker/buildx/releases/download/v0.13.1/buildx-v0.13.1.linux-${ARCH} -o buildx-v0.13.1.linux-${ARCH} && \
    chmod +x buildx-v0.13.1.linux-${ARCH} && \
    mv buildx-v0.13.1.linux-${ARCH} /usr/local/bin/buildx
    
ENV DAPPER_ENV="REPO PUSH TAG DRONE_TAG ARCH"
ENV DAPPER_SOURCE=/go/src/github.com/kiagnose/kubevirt-storage-checkup
ENV DAPPER_OUTPUT="./bin"
ENV DAPPER_DOCKER_SOCKET=true
WORKDIR ${DAPPER_SOURCE}

ENTRYPOINT ["./scripts/entry"]
CMD ["ci"]